# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6330d429b4b4caab8331ebc4aa78f63682580e031e0e6a5950df2484d0d1b1cf78f5e72f0fe39a5083e34c2f399b5f7a78226bef9c3791c42b8ae179ee041f85

test:
  secret_key_base: 2afe58deb144c1e764c2972944f6af70b4d1e2f5fa42ff7df1ea76fe9f432d51bb024f4149c6fd33538b4421804fb289d2ca092817b0aa10f275acee3099ddcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
